name: gradle-ci

on: [push, pull_request, workflow_dispatch]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest

  strategy:
   matrix:
     java-version: [ 11, 17, 19 ]

  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run build with Gradle Wrapper
      run: ./gradlew build check --stacktrace